### PR TITLE
update to elm 0.18.0

### PR DESCRIPTION
**Pull request by thomvil**
In commit `2249dc80e1605bf7a098ac9c9c3f1143ac469731` authToken was removed from the `bootstrap.py` script. It was however still included in the Readme.

### CODE REVIEW

**Comment by eeue56** [comment]
it would be more useful to update this to 0.18, I think :)

**Comment by thomvil** [comment]
@eeue56 i'll give it a go. (But wouldn't it be cleaner to separate that in a new PR?)

**Comment by thomvil** [comment]
@eeue56 Could you take a look at the changes I proposed? Please take into account I have very little experience with Elm as of yet. (Also with PR for that matter.)

**Comment by eeue56** [comment]
lgmt!

**Pull request merged**
